### ISSUE TITLE
Cannot estimate registration

### ISSUE THREAD

**Issue by ziw-liu** [czbiohub-sf/biahub#22]
After clicking 6-pairs of points on the same Z-plane for a similarity transform, the skimage geometric function errors out:

```
(biahub) /hpc/projects/comp.micro/virtual_staining/datasets/test/hipsc/2024_11_25_ATP1B3_Hoechst/1-preprocess/0-register/beads biahub estimate-registration -s beads_cropped.zarr/0/0/0 -t beads_cropped.zarr/0/0/0 -x -o DAPI-to-GFP.yaml

Target channel INFO:
Zarr hierarchy:
/
 └── 0 (1, 3, 79, 2016, 2016) float32

=== Summary ===
Format:                  omezarr v0.4
Axes:                    T (time); C (channel); Z (space); Y (space); X (space); 
Channel names:           ['PrimeBSI_GFP', 'PrimeBSI_DAPI', 'Zyla_BF']
(Z, Y, X) scale (um):    (0.20000000000000018, 0.206, 0.206)
Chunk size:              (1, 1, 20, 2016, 2016)
No. bytes decompressed:          3852914688 [3.6 GiB]

Source channel INFO:
Zarr hierarchy:
/
 └── 0 (1, 3, 79, 2016, 2016) float32

=== Summary ===
Format:                  omezarr v0.4
Axes:                    T (time); C (channel); Z (space); Y (space); X (space); 
Channel names:           ['PrimeBSI_GFP', 'PrimeBSI_DAPI', 'Zyla_BF']
(Z, Y, X) scale (um):    (0.20000000000000018, 0.206, 0.206)
Chunk size:              (1, 1, 20, 2016, 2016)
No. bytes decompressed:          3852914688 [3.6 GiB]

Enter target channel index: 0
Enter source channel index: 1
Rotate the source channel by 90 degrees? (0, 1, or -1): 0
/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/waveorder/focus.py:96: PeakPropertyWarning: some peaks have a prominence of 0
  peak_results = peak_widths(midband_sum, [peak_index])
/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/waveorder/focus.py:96: PeakPropertyWarning: some peaks have a width of 0
  peak_results = peak_widths(midband_sum, [peak_index])
Could not determine best source channel focus slice, using 39
Best target channel focus slice: 58
Z scaling factor: 1.000; XY scaling factor: 1.000

Add at least three points in the two channels by sequentially clicking on a feature in the source channel and its corresponding feature in target channel. Select grid mode if you prefer side-by-side view. Press <enter> when done...
Traceback (most recent call last):
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/bin/biahub", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ziwen.liu/biahub/biahub/cli/estimate_registration.py", line 289, in estimate_registration
    transform.estimate(pts_source_channel_data, pts_target_channel_data)
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/skimage/transform/_geometric.py", line 1516, in estimate
    self.params = _umeyama(src, dst, estimate_scale=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/ziwen.liu/anaconda/2022.05/x86_64/envs/biahub/lib/python3.11/site-packages/skimage/transform/_geometric.py", line 144, in _umeyama
    A = dst_demean.T @ src_demean / num
        ~~~~~~~~~~~~~^~~~~~~~~~~~
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 11 is different from 6)
WARNING: QThread: Destroyed while thread is still running
WARNING:vispy:QThread: Destroyed while thread is still running
[1]    4146240 abort (core dumped)  biahub estimate-registration -s beads_cropped.zarr/0/0/0 -t  -x -o 
```

**Comment by Soorya19Pradeep** [comment]
@ziw-liu , @edyoshikun , I am getting the same error. @ieivanov , @tayllatheodoro, is this error fixed in any branch?

**Comment by ieivanov** [comment]
@Soorya19Pradeep Let's take a look at this together. There is an expected / proper way to click through points, which may not be very intuitive. We can improve on our documentation and user guidance and properly catch errors

**Comment by Soorya19Pradeep** [comment]
Thanks @ieivanov! I went over the code with @talonchandler and found that two methods are used for transform computation, similarity and Euclidean. I understood that similarity is useful when there is no tilt in FOV in z if we click the points in the selected z slice for each channel. If we click across multiple z slices, this doesn't work. On the other hand Euclidean works when there is tilt in z and we click across z slices for the same channel. 

I did not set the `affine_transform_type` parameter on the input config, which defaulted to `Similarity`, and I had a tilt in the z-axis, which is why I got the error. 

Is this by design, or should the default be changed?

**Comment by Soorya19Pradeep** [comment]
@talonchandler pointed out that Similarity can handle that since it would require rescaling. The function used for similarity handles 2D data. So we will need to accommodate for 3D. @ieivanov is that correct?
